php:
  build: images/centos
  volumes:
    - "./:/var/www/html"
    - "./bin/composer.phar:/usr/local/bin/composer"
    - "./conf/php.ini:/etc/php.ini"
  working_dir: /var/www/html
  ports:
    - "8888:80"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
   - PMA_ARBITRARY=1
   - UPLOAD_SIZE=10G
  restart: always
  ports:
   - 8080:80
  volumes:
   - /sessions
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp
